from pathlib import Path
import json, datetime

def read(path): return json.loads(Path(path).read_text())
def write(path, value): Path(path).write_text(json.dumps(value, ensure_ascii=False, indent=2)+'\n')
baseline=read('phases/phase-67-2026-09-27-baseline.json')
registry=read('sources/registry.json'); coverage=read('data/published/coverage.json')
assert registry==baseline['registry'] and coverage==baseline['coverage']
outcomes=read('data/discovery/latin-america-public-sources-2026-09-27-fetch-outcomes.json')
assert len(outcomes)==26
records=[
 dict(id='ar-concursar-public-recruitment', country='AR', name='Argentina — CONCURSAR public recruitment', authority='Ministry of Deregulation and State Transformation, Argentina', homepage='https://www.argentina.gob.ar/desregulacion/transformacion-del-estado-y-funcion-publica/desarrollo-y-modernizacion-del-empleo-26',
 appointmentType='museum executive-function selection; permanent or fixed-term tenure not established',
 summary='Retained 2026 museum call covers five executive-function posts. Registration ran 24 August 10:00 to 7 September 17:00; official timezone unverified. Museo Historico Nacional bases require Argentine nationality by birth, naturalisation or option, with a reasoned Chief of Cabinet exception. Foreign applicants need evidence that an exception applies; open public/private competition does not remove nationality, degree or experience conditions. Mandatory reading/comprehension of at least one role-relevant foreign language is stated, without a named language, CEFR level or certificate threshold. General digital FAQ and current original-document instructions require reconciliation.',
 gap='No adapter or reviewed cycle. Other four museum bases and amendments remain unretained. Resolve current-versus-general document instructions, citizenship exception authority, appointment duration, fees, timezone, selection venues and complete role requirements. Five posts do not automatically equal five cycles; applicant-result registers are outside opportunity collection.',
 international='needs verification: explicit nationality condition with authorised exception, not blanket foreign-applicant permission',
 language='mandatory role-relevant foreign-language reading/comprehension; language and formal level unspecified',
 evidenceLabels=['museum-historico-2026-bases','museum-call-2026']),
 dict(id='pe-servir-talento-peru', country='PE', name='Peru — SERVIR Talento Peru public jobs and practices', authority='National Civil Service Authority (SERVIR), Peru', homepage='https://www.gob.pe/institucion/servir/campa%C3%B1as/4782-talento-peru',
 appointmentType='public jobs and professional/preprofessional practices; employer-specific regimes',
 summary='Retained SERVIR campaign and service pages refer to public-sector jobs and professional/preprofessional practices. Employers register vacancies; jobseekers follow individual employer notices. SERVIR employer page separates Civil Service Law, CAS and practice routes. Practice participation does not guarantee a government appointment or vocational qualification. Publication duration is separate from application dates. Foreign-citizen eligibility and formal language levels remain unverified; Spanish interface cannot establish a proficiency requirement.',
 gap='No adapter or reviewed cycle. Retained authority referral points to app.servir.gob.pe/DifusionOfertasExterno/faces/consultas/ofertas_laborales.xhtml; live application data and employer notices still require collection. Verify nationality, residence, education equivalence, tenure, language, application window/timezone, fees and venue per notice. Posting obligation is not a completeness audit.',
 international='needs verification: no notice-level foreign-applicant rule retained', language='formal language requirement unverified', evidenceLabels=['authority-campaign','authority-service-referral','servir-employer-routes']),
 dict(id='ec-encuentraempleo-public-contests', country='EC', name='Ecuador — Encuentra Empleo public contests', authority='Ministry of Labour, Ecuador', homepage='https://encuentraempleo.trabajo.gob.ec/',
 appointmentType='public merit/opposition selection within a mixed public/private employment service; tenure unverified',
 summary='Official-reader observations identify Ministry employment service and a public merit/opposition route. Exact-byte requests failed. Selection authority page is an administrative human-resources login, not a public applicant catalogue. Refugee/migrant services and private vacancies cannot prove eligibility for public service. Current foreign-citizen permission and language levels remain unverified. Reader notes newer selection regulations, so historical FAQ rules need reconciliation before extraction.',
 gap='All three exact-byte requests failed at robots access. No retained original, adapter or reviewed cycle. Obtain current official applicant catalogue, notice originals, governing amendments and public/private classification. Verify nationality, residence, language, tenure, qualifications, dates/timezones, fees and actual selection venues; never infer application status from a login screen.',
 international='needs verification: official-reader discovery only; no retained notice', language='formal language requirement unverified', evidenceLabels=[]),
 dict(id='uy-onsc-uruguay-concursa', country='UY', name='Uruguay — ONSC Uruguay Concursa public recruitment', authority='National Civil Service Office (ONSC), Uruguay', homepage='https://www.gub.uy/tramites/uruguay-concursa',
 appointmentType='multiple public employment/traineeship contracts; Soriano masonry precedence list described as contracted',
 summary='Retained government referral distinguishes central and employer-managed recruitment and multiple contract routes. Official-reader Soriano masonry call 8184/2026 states natural or legal Uruguayan citizenship; original vacancy retention failed, so this remains provisional. Legal citizenship is distinct from foreign nationality alone. Retained citizenship service requires Spanish understanding/expression for foreign-language applicants, without CEFR level; that is a citizenship procedure, not a universal job exam requirement. Precedence lists do not guarantee immediate appointment.',
 gap='Soriano original request failed because robots response was non-text. No adapter or reviewed cycle. Retain current notice/bases and amendments before accepting indexed 24 September–8 October dates or citizenship/contract terms. Relative cached opening labels are not current status. Verify all application, selection and appointment conditions, fees, cutoff timezone and venues. Citizenship service is supporting context only.',
 international='needs verification: reader-only citizenship condition; legal-citizenship route must be assessed separately', language='Spanish comprehension/expression in citizenship procedure; no universal recruitment level inferred', evidenceLabels=['government-referral','legal-citizenship-service']),
 dict(id='cr-dgsc-public-recruitment', country='CR', name='Costa Rica — DGSC public recruitment and eligible registers', authority='Directorate General of Civil Service (DGSC), Costa Rica', homepage='https://vacantes.dgsc.go.cr/',
 appointmentType='civil-service applicant and eligible registers plus employer vacancies; tenure per role unresolved',
 summary='Retained DGSC pages separate applicant registers from eligible registers after suitability assessment. Eligible registration creates participation expectations, not guaranteed employment. Vacancy page includes current cards and extensive historical hidden notices; raw DOM entries must not all become current cycles. FAQ assigns teaching processes to Ministry of Public Education and allows role-specific complementary knowledge/language checks. No universal CEFR requirement or foreign-citizen permission verified. Work locations remain distinct from selection venues.',
 gap='No adapter or reviewed cycle. Reconcile rendered current vacancies against historical modals and institution-specific notices. DGSC route is not complete government employer coverage; teaching and other regimes require separate authorities. Verify notice-specific nationality, residence, age, qualifications, language, tenure, dates/timezones, fees and venues.',
 international='needs verification: no notice-level foreign-applicant permission established', language='role-specific language knowledge may be tested; no universal named language or certificate level verified', evidenceLabels=['vacancy-register','applicant-eligible-registers','authority-faq']),
 dict(id='do-map-concursa', country='DO', name='Dominican Republic — MAP CONCURSA public recruitment', authority='Ministry of Public Administration (MAP), Dominican Republic', homepage='https://map.gob.do/Concursa/',
 appointmentType='immediate environmental-educator vacancy versus future eligible registers; definitive tenure unverified',
 summary='Retained environmental-educator September 2026 notice explicitly requires Dominican nationality, relevant degree and one year of experience. External competition does not mean international eligibility. Documents accepted 22–28 September, 08:00–16:00; timezone not printed. Receipt confirmation precedes jury admission; fuller bases are available only after admission. Work address is not an exam venue. Separate disability-inclusive Labour Relations Analyst notice creates an eligible register, also requires Dominican nationality, and closed 3 August at 15:00. No formal language level established.',
 gap='No adapter or reviewed cycle. Preserve independent immediate-vacancy and future-register identities; portal result/seat counts are not application-cycle totals. Confirm amendments and tenure, current notice hierarchy, fees and official cutoff timezone. Full selection bases are available only after admission and remain an evidence gap. Nationality conditions apply to these notices, not every public-sector role.',
 international='does not match the explicit nationality condition for applicants without Dominican nationality in the two retained notices; other conditions and later stages still require review', language='no formal proficiency level established in retained notices', evidenceLabels=['environmental-educator-september-2026','inclusive-labour-relations-register-2026','public-contests','inclusive-register-2026']),
 dict(id='py-mef-paraguay-concursa', country='PY', name='Paraguay — MEF Paraguay Concursa recruitment referrals', authority='Ministry of Economy and Finance, Paraguay', homepage='https://www.paraguayconcursa.gov.py/',
 appointmentType='public appointment competitions and restricted internal promotion; current tenure unverified',
 summary='Retained MEF authority page identifies Paraguay Concursa. Retained employer register separates public opposition from internal promotion. Its June 2026 internal-promotion publication window is 26–30 June; applications ran 2–8 July, a different window now closed. Internal competitions cannot become general public applications. INAPP training for existing officials is not proof of an open vocational qualification. Foreign-applicant permission and formal Spanish/Guarani levels remain unverified.',
 gap='Central portal exact-byte request failed at robots fetch. No adapter or reviewed cycle. Retain central listings and original employer bases/amendments. Keep publication and application dates separate, historical entries historical, and internal eligibility distinct. Verify nationality, residence, education, language, tenure, fees, timezone and venues; MEF alone is not complete national authority coverage.',
 international='needs verification: internal promotion and public opposition have different participant rules', language='formal Spanish/Guarani proficiency requirements unverified', evidenceLabels=['authority-referral','employer-contests']),
 dict(id='gt-onsec-guatempleo', country='GT', name='Guatemala — ONSEC GUATEMPLEO public recruitment', authority='National Civil Service Office (ONSEC), Guatemala', homepage='https://guatempleo.siarh.gob.gt/',
 appointmentType='government vacancy service identified through historical official referral; current appointment terms unverified',
 summary='Official-reader indexing identifies ONSEC 2019 anniversary publication referring to GUATEMPLEO for CV, vacancy application and status. This historical referral does not establish a current 2026 intake. ONSEC homepage, portal and historical publication exact-byte requests all failed HTTP 403 at robots access. Foreign-citizen permission, language levels and current appointment types remain unverified; registration ability is not eligibility evidence.',
 gap='All three requests failed; no retained original, adapter or reviewed cycle. Obtain current official portal referral and notice/bases, resolve permitted access, then verify nationality, residence, age, qualifications, language, tenure, window/timezone, fees and venues. Historical publication date cannot be replaced by search-engine crawl date. Current notice access remains unresolved.',
 international='needs verification: historical authority discovery only', language='formal language requirement unverified', evidenceLabels=[]),
]
matrix={'researchDate':'2026-09-27','notPublishedEligibility':True,'sourceCountIsNotCycleCount':True,'translationAcceptance':'pending-human-review','sources':[]}
for row in records:
 documents=[x for x in outcomes if x['sourceId']==row['id']]
 discovered=next((x['url'] for x in documents if x['label']==row['evidenceLabels'][0]),row['homepage']) if row['evidenceLabels'] else row['homepage']
 assert not any(x['id']==row['id'] for x in registry['sources'])
 registry['sources'].append(dict(id=row['id'],name=row['name'],country=row['country'],authority=row['authority'],homepage=row['homepage'],discoveredFrom=discovered,discoveredAt='2026-09-27',connector='none',cadenceHours=24,licence='Official-source discovery for internal research; reuse/access terms require review before automated collection.',notes=row['summary'],accessGap=row['gap'],enabled=False,reviewRequired=True))
 assert not any(x['jurisdictionCode']==row['country'] for x in coverage)
 coverage.append(dict(jurisdictionCode=row['country'],fixture=False,status='no-verified-listings',researchedAuthorities=[row['authority']],connectedSourceCount=0,unresolvedGaps=[row['name']+': '+row['gap']],lastSuccessfulFetchAt=None,lastValidatedAt=None))
 matrix['sources'].append(dict(sourceId=row['id'],country=row['country'],pathways=['recruitment'],status='research-only-awaiting-review',appointmentType=row['appointmentType'],summary=row['summary'],unresolved=row['gap'],internationalApplicantAssessment=row['international'],languageAssessment=row['language'],threeStageEligibility={'canApply':'needs verification: complete criteria not accepted','canEnterSelection':'needs verification: admission conditions not accepted','canObtainJobOrLicence':'needs verification: resulting appointment conditions not accepted'},documents=documents))
write('sources/registry.json',registry);write('data/published/coverage.json',coverage)
write('data/discovery/latin-america-public-source-matrix-2026-09-27.json',matrix)
write('data/discovery/latin-america-public-sources-2026-09-27-research.json',dict(researchedAt=datetime.datetime.now(datetime.timezone.utc).isoformat(),localDate='2026-09-27',scope='Eight official recruitment sources in AR, PE, EC, UY, CR, DO, PY and GT; discovery is not verified opportunity publication.',method='Primary official-reader/index research and retained originals. Exact-byte requests use existing HTTPS, robots, throttle and TLS policy. Failed access remains explicit. No collector health, review-packet or publication changes.',matrix='data/discovery/latin-america-public-source-matrix-2026-09-27.json',outcomes='data/discovery/latin-america-public-sources-2026-09-27-fetch-outcomes.json',readerOnly=[{'sourceId':'uy-onsc-uruguay-concursa','url':'https://www.uruguayconcursa.gub.uy/llamado/43217','observation':'Indexed Soriano call 8184/2026: contracted masonry precedence list, natural/legal citizenship, 24 September–8 October dates. Original retention failed; fields remain provisional.'},{'sourceId':'ec-encuentraempleo-public-contests','url':'https://selecciondepersonal.trabajo.gob.ec/','observation':'Official reader shows administrative UATH login and newer selection regulations. Not evidence of public vacancy rows.'},{'sourceId':'gt-onsec-guatempleo','url':'https://www.onsec.gob.gt/w1/wp-content/uploads/2019/10/Revista-ONSEC-Aniversario-2019-FINAL.pdf','observation':'Historical 2019 official-index referral only. Current window unverified; original retention failed.'}],originalsRetained=sum(x['status']=='retained' for x in outcomes),failedRequests=sum(x['status']=='failed' for x in outcomes),collectionJobs=0,publicationDecisions=0))
print(json.dumps({'sources':len(registry['sources']),'jurisdictions':len(coverage),'newSources':len(records),'originals':18,'failures':8}))
