/**
 * Demo records. Nothing here is a live notice: dates, rules, venues, and coverage
 * are illustrative and exist so the interface can be exercised before real data
 * is published. Shown only in demo mode or while no verified data exists.
 */
import type { EligibilityRules } from "./eligibility/types.ts";
import type { CoverageRecord, OpportunityCycle, SourceEvidence } from "./opportunities.ts";

const demoEvidence = "Demo criterion — not taken from a real notice.";

const indiaCentral: EligibilityRules = {
  complete: true,
  asOn: "2026-08-01",
  age: {
    min: 21,
    max: 32,
    relaxations: [
      { category: "obc", years: 3 },
      { category: "sc", years: 5 },
      { category: "st", years: 5 },
      { disability: true, years: 10 },
      { exServiceman: true, years: 5 },
    ],
    evidence: demoEvidence,
  },
  education: { minLevel: "bachelor", finalYearAllowed: true, evidence: demoEvidence },
  nationality: { allowed: ["IN"], conditional: ["NP", "BT"], evidence: demoEvidence },
  attempts: { max: 6, byCategory: { obc: 9, sc: null, st: null }, evidence: demoEvidence },
  manualChecks: [{ stage: "outcome", text: "Medical examination and document verification before appointment." }],
};

const fixtureRules: Record<string, EligibilityRules> = {
  "in-civil-service-2026": indiaCentral,
  "in-nursing-license-2026": {
    complete: true,
    asOn: "2026-10-01",
    education: { minLevel: "diploma", fields: ["nursing"], finalYearAllowed: false, evidence: demoEvidence },
    nationality: { allowed: ["IN"], evidence: demoEvidence },
    manualChecks: [{ stage: "outcome", text: "Registration with the state nursing council." }],
  },
  "in-technical-admission-2026": {
    complete: true,
    asOn: "2026-07-01",
    age: { max: 25, relaxations: [{ category: "sc", years: 5 }, { category: "st", years: 5 }, { disability: true, years: 5 }], evidence: demoEvidence },
    education: { minLevel: "higher-secondary", finalYearAllowed: true, evidence: demoEvidence },
  },
  "us-federal-analyst-2026": {
    complete: true,
    asOn: "2026-10-03",
    nationality: { allowed: ["US"], evidence: demoEvidence },
    education: { minLevel: "bachelor", evidence: demoEvidence },
    manualChecks: [{ stage: "outcome", text: "Background investigation and security clearance." }],
  },
  "us-engineering-license-2026": {
    complete: true,
    asOn: null,
    education: { minLevel: "bachelor", fields: ["engineering"], evidence: demoEvidence },
    experience: { minYears: 4, evidence: demoEvidence },
  },
  "us-apprenticeship-2026": {
    complete: true,
    asOn: "2026-10-20",
    age: { min: 18, evidence: demoEvidence },
    education: { minLevel: "secondary", evidence: demoEvidence },
    residence: { countries: ["US"], evidence: demoEvidence },
  },
  "gb-civil-service-2026": {
    complete: true,
    asOn: "2026-09-01",
    nationality: { allowed: ["GB", "IE"], conditional: ["FR", "DE", "ES", "IT", "PL", "IN", "PK", "NG"], evidence: demoEvidence },
    education: { minLevel: "bachelor", finalYearAllowed: true, evidence: demoEvidence },
  },
  "gb-teaching-admission-2026": {
    complete: true,
    asOn: "2026-09-01",
    education: { minLevel: "bachelor", finalYearAllowed: true, evidence: demoEvidence },
    manualChecks: [{ stage: "selection", text: "Enhanced background check before school placements." }],
  },
  "br-public-health-2026": {
    complete: true,
    asOn: "2026-09-30",
    age: { min: 18, evidence: demoEvidence },
    nationality: { allowed: ["BR"], conditional: ["PT"], evidence: demoEvidence },
    education: { minLevel: "bachelor", fields: ["health", "public health", "nursing", "medicine"], evidence: demoEvidence },
  },
  "br-technical-training-2026": {
    complete: true,
    asOn: "2026-11-01",
    age: { min: 16, evidence: demoEvidence },
    education: { minLevel: "secondary", finalYearAllowed: true, evidence: demoEvidence },
  },
  "fr-health-admission-2026": {
    complete: true,
    asOn: "2026-09-01",
    education: { minLevel: "higher-secondary", finalYearAllowed: true, evidence: demoEvidence },
  },
  "fr-accountancy-license-2026": {
    complete: true,
    asOn: "2026-06-30",
    education: { minLevel: "master", fields: ["accounting", "finance"], evidence: demoEvidence },
    experience: { minYears: 3, evidence: demoEvidence },
  },
  "jp-engineering-admission-2026": {
    complete: true,
    asOn: "2027-04-01",
    education: { minLevel: "higher-secondary", finalYearAllowed: true, evidence: demoEvidence },
    manualChecks: [{ stage: "selection", text: "Japanese language ability at the level stated in the guide." }],
  },
};

const sampleSource = (
  id: string,
  authority: string,
  language: string,
  format: SourceEvidence["format"],
  fetchedAt: string | null = "2026-09-24T08:00:00Z",
): SourceEvidence => ({
  id: `source-${id}`,
  title: "Synthetic prototype notice",
  authority,
  language,
  format,
  url: null,
  lastSuccessfulFetchAt: fetchedAt,
  lastValidatedAt: fetchedAt,
  verificationStatus: "fixture",
});

type Seed = Omit<OpportunityCycle, "fixture" | "lastVerifiedAt" | "applicationUrl" | "rules">;
const cycle = (seed: Seed): OpportunityCycle => ({
  ...seed,
  rules: fixtureRules[seed.id] ?? null,
  fixture: true,
  lastVerifiedAt: null,
  applicationUrl: null,
});

export const fixtureOpportunities: OpportunityCycle[] = [
  cycle({
    id: "in-civil-service-2026",
    title: "Civil service officer intake",
    cycleLabel: "2026 cycle",
    programme: "National civil service intake",
    authority: "Sample national recruitment authority",
    pathway: "recruitment",
    status: "open",
    statusNote: "Applications shown open in prototype scenario.",
    jurisdictionCode: "IN",
    jurisdictionName: "India",
    scopeLabel: "Nationwide recruitment",
    outcome: "Civil service appointment",
    applicationWindow: { opensOn: "2026-09-12", closesOn: "2026-10-15", officialTimeZone: "Asia/Kolkata", cutoffLocalTime: null, precision: "date" },
    qualifications: "Bachelor's degree (sample rule)",
    citizenshipRule: "Nationality rule requires official confirmation.",
    residenceRule: "Residence rule requires official confirmation.",
    selectionStages: ["Written examination", "Interview"],
    fee: "Fee not verified",
    venues: [{ kind: "unknown", name: "Exam venues not published in this fixture" }],
    sources: [sampleSource("in-civil-service-2026", "Sample national recruitment authority", "English", "HTML")],
    changes: [{ at: "2026-09-12", kind: "created", summary: "Illustrative opening added." }],
  }),
  cycle({
    id: "in-nursing-license-2026",
    title: "Nursing registration examination",
    cycleLabel: "Autumn 2026",
    programme: "Nursing registration",
    authority: "Sample state licensing board",
    pathway: "licensing",
    status: "extended",
    statusNote: "Illustrative deadline extension from 25 September to 1 October.",
    jurisdictionCode: "IN",
    jurisdictionName: "India",
    scopeLabel: "State licensing scope",
    outcome: "Eligibility for professional nursing registration",
    applicationWindow: { opensOn: "2026-08-25", closesOn: "2026-10-01", officialTimeZone: "Asia/Kolkata", cutoffLocalTime: "17:00", precision: "minute" },
    qualifications: "Approved nursing qualification (sample rule)",
    citizenshipRule: "No citizenship determination in sample evidence.",
    residenceRule: "State registration rule needs verification.",
    selectionStages: ["Credential review", "Examination"],
    fee: "Sample fee: ₹1,200",
    venues: [{ kind: "published", name: "Sample examination centre", city: "Mumbai", latitude: 19.076, longitude: 72.8777 }],
    sources: [sampleSource("in-nursing-license-2026", "Sample state licensing board", "English", "PDF")],
    changes: [{ at: "2026-09-20", kind: "extended", summary: "Illustrative closing date moved from 25 September to 1 October." }],
  }),
  cycle({
    id: "in-technical-admission-2026",
    title: "Technical institute entrance",
    cycleLabel: "2026 admission",
    programme: "Technical degree admission",
    authority: "Sample admissions authority",
    pathway: "admission",
    status: "closed",
    statusNote: "Sample application window ended 10 September.",
    jurisdictionCode: "IN",
    jurisdictionName: "India",
    scopeLabel: "Multi-campus admission",
    outcome: "Admission to technical degree programme",
    applicationWindow: { opensOn: "2026-08-01", closesOn: "2026-09-10", officialTimeZone: "Asia/Kolkata", cutoffLocalTime: null, precision: "date" },
    qualifications: "Upper secondary qualification (sample rule)",
    citizenshipRule: "International categories need verification.",
    residenceRule: "No residence determination in sample evidence.",
    selectionStages: ["Entrance examination", "Counselling"],
    fee: "Fee not verified",
    venues: [{ kind: "unknown", name: "Venues pending publication" }],
    sources: [sampleSource("in-technical-admission-2026", "Sample admissions authority", "Hindi", "scanned PDF")],
    changes: [{ at: "2026-08-01", kind: "created", summary: "Illustrative admission cycle added." }],
  }),
  cycle({
    id: "us-federal-analyst-2026",
    title: "Federal policy analyst intake",
    cycleLabel: "2026 posting",
    programme: "Federal analyst recruitment",
    authority: "Sample federal agency",
    pathway: "recruitment",
    status: "open",
    statusNote: "Applications shown open in prototype scenario.",
    jurisdictionCode: "US",
    jurisdictionName: "United States",
    scopeLabel: "Federal hiring scope",
    outcome: "Policy analyst employment",
    applicationWindow: { opensOn: "2026-09-18", closesOn: "2026-10-03", officialTimeZone: "America/New_York", cutoffLocalTime: "23:59", precision: "minute" },
    qualifications: "Relevant degree or equivalent experience (sample rule)",
    citizenshipRule: "Citizenship requirement needs official confirmation.",
    residenceRule: "Work location requirement needs confirmation.",
    selectionStages: ["Application review", "Interview"],
    fee: "No fee shown in sample",
    venues: [{ kind: "published", name: "Sample duty station", city: "Washington, DC", latitude: 38.9072, longitude: -77.0369 }],
    sources: [sampleSource("us-federal-analyst-2026", "Sample federal agency", "English", "HTML")],
    changes: [{ at: "2026-09-18", kind: "created", summary: "Illustrative posting added." }],
  }),
  cycle({
    id: "us-engineering-license-2026",
    title: "Professional engineering examination",
    cycleLabel: "Fall 2026",
    programme: "Engineering licence examination",
    authority: "Sample state licensing board",
    pathway: "licensing",
    status: "uncertain",
    statusNote: "Conflicting sample notices require reviewer decision; previous state retained.",
    jurisdictionCode: "US",
    jurisdictionName: "United States",
    scopeLabel: "State regulatory scope",
    outcome: "Professional engineering licence eligibility",
    applicationWindow: { opensOn: "2026-09-01", closesOn: null, officialTimeZone: "America/Chicago", cutoffLocalTime: null, precision: "unknown", note: "Conflicting deadline in sample evidence." },
    qualifications: "Accredited degree and experience (sample rule)",
    citizenshipRule: "No citizenship determination in sample evidence.",
    residenceRule: "State rule needs verification.",
    selectionStages: ["Credential review", "Examination"],
    fee: "Fee not verified",
    venues: [{ kind: "unknown", name: "Testing centre not published" }],
    sources: [sampleSource("us-engineering-license-2026", "Sample state licensing board", "English", "PDF")],
    changes: [{ at: "2026-09-23", kind: "eligibility", summary: "Illustrative conflicting experience criteria flagged for review." }],
  }),
  cycle({
    id: "us-apprenticeship-2026",
    title: "Advanced manufacturing apprenticeship",
    cycleLabel: "Autumn 2026",
    programme: "Manufacturing apprenticeship",
    authority: "Sample public workforce office",
    pathway: "vocational",
    status: "open",
    statusNote: "Applications shown open in prototype scenario.",
    jurisdictionCode: "US",
    jurisdictionName: "United States",
    scopeLabel: "Regional workforce programme",
    outcome: "Recognised vocational qualification",
    applicationWindow: { opensOn: "2026-09-20", closesOn: "2026-11-02", officialTimeZone: "America/Los_Angeles", cutoffLocalTime: null, precision: "date" },
    qualifications: "Secondary school completion (sample rule)",
    citizenshipRule: "Work authorisation needs verification.",
    residenceRule: "Regional placement rule needs verification.",
    selectionStages: ["Online screening", "Practical assessment"],
    fee: "No fee shown in sample",
    venues: [{ kind: "online", name: "Initial screening online" }, { kind: "unknown", name: "Practical assessment venue pending" }],
    sources: [sampleSource("us-apprenticeship-2026", "Sample public workforce office", "English", "HTML")],
    changes: [{ at: "2026-09-20", kind: "created", summary: "Illustrative vocational intake added." }],
  }),
  cycle({
    id: "gb-civil-service-2026",
    title: "Civil service graduate intake",
    cycleLabel: "2026 cohort",
    programme: "Graduate civil service recruitment",
    authority: "Sample central recruitment team",
    pathway: "recruitment",
    status: "closed",
    statusNote: "Sample application window ended 18 September.",
    jurisdictionCode: "GB",
    jurisdictionName: "United Kingdom",
    scopeLabel: "UK-wide recruitment",
    outcome: "Civil service graduate placement",
    applicationWindow: { opensOn: "2026-08-20", closesOn: "2026-09-18", officialTimeZone: "Europe/London", cutoffLocalTime: "12:00", precision: "minute" },
    qualifications: "Degree or equivalent (sample rule)",
    citizenshipRule: "Nationality categories need verification.",
    residenceRule: "Residency check required for some roles (sample rule).",
    selectionStages: ["Online assessment", "Assessment centre"],
    fee: "No fee shown in sample",
    venues: [{ kind: "online", name: "Initial assessment online" }],
    sources: [sampleSource("gb-civil-service-2026", "Sample central recruitment team", "English", "HTML")],
    changes: [{ at: "2026-08-20", kind: "created", summary: "Illustrative recruitment cycle added." }],
  }),
  cycle({
    id: "gb-health-registration-2026",
    title: "Allied health registration assessment",
    cycleLabel: "Autumn 2026",
    programme: "Allied health registration",
    authority: "Sample professional regulator",
    pathway: "licensing",
    status: "stale",
    statusNote: "Sample source missed more than two daily checks; opening cannot be inferred from silence.",
    jurisdictionCode: "GB",
    jurisdictionName: "United Kingdom",
    scopeLabel: "UK regulatory scope",
    outcome: "Professional registration eligibility",
    applicationWindow: { opensOn: "2026-09-01", closesOn: "2026-10-08", officialTimeZone: "Europe/London", cutoffLocalTime: null, precision: "date" },
    qualifications: "Recognised allied health qualification (sample rule)",
    citizenshipRule: "No citizenship determination in sample evidence.",
    residenceRule: "Practice location requirements need verification.",
    selectionStages: ["Qualification review", "Assessment"],
    fee: "Fee not verified",
    venues: [{ kind: "unknown", name: "Venue not published" }],
    sources: [sampleSource("gb-health-registration-2026", "Sample professional regulator", "English", "PDF", "2026-09-19T08:00:00Z")],
    changes: [{ at: "2026-09-22", kind: "source-failure", summary: "Illustrative source checks failed; last published revision retained." }],
  }),
  cycle({
    id: "gb-teaching-admission-2026",
    title: "Teacher training admission",
    cycleLabel: "2027 intake",
    programme: "Initial teacher education",
    authority: "Sample public admissions service",
    pathway: "admission",
    status: "open",
    statusNote: "Applications shown open in prototype scenario.",
    jurisdictionCode: "GB",
    jurisdictionName: "United Kingdom",
    scopeLabel: "England admission scope",
    outcome: "Admission to teacher qualification programme",
    applicationWindow: { opensOn: "2026-09-10", closesOn: "2026-10-12", officialTimeZone: "Europe/London", cutoffLocalTime: null, precision: "date" },
    qualifications: "Undergraduate degree (sample rule)",
    citizenshipRule: "International applicant categories need verification.",
    residenceRule: "Placement eligibility needs verification.",
    selectionStages: ["Application review", "Interview"],
    fee: "Fee not verified",
    venues: [{ kind: "unknown", name: "Interview format pending" }],
    sources: [sampleSource("gb-teaching-admission-2026", "Sample public admissions service", "English", "HTML")],
    changes: [{ at: "2026-09-10", kind: "created", summary: "Illustrative admissions cycle added." }],
  }),
  cycle({
    id: "br-public-health-2026",
    title: "Public health analyst concurso",
    cycleLabel: "Edital 2026",
    programme: "Public health recruitment",
    authority: "Sample state health secretariat",
    pathway: "recruitment",
    status: "cancelled",
    statusNote: "Illustrative official cancellation; retained in history.",
    jurisdictionCode: "BR",
    jurisdictionName: "Brazil",
    scopeLabel: "State hiring scope",
    outcome: "Public health analyst appointment",
    applicationWindow: { opensOn: "2026-08-15", closesOn: "2026-09-30", officialTimeZone: "America/Sao_Paulo", cutoffLocalTime: null, precision: "date" },
    qualifications: "Relevant university degree (sample rule)",
    citizenshipRule: "Nationality requirement needs verification.",
    residenceRule: "No residence determination in sample evidence.",
    selectionStages: ["Written examination", "Document review"],
    fee: "Sample fee: R$80",
    venues: [{ kind: "published", name: "Sample public examination centre", city: "São Paulo", latitude: -23.5505, longitude: -46.6333 }],
    sources: [sampleSource("br-public-health-2026", "Sample state health secretariat", "Portuguese", "PDF")],
    changes: [{ at: "2026-09-22", kind: "cancelled", summary: "Illustrative cancellation notice published." }],
  }),
  cycle({
    id: "br-technical-training-2026",
    title: "Federal technical training entrance",
    cycleLabel: "2027 intake",
    programme: "Technical qualification admission",
    authority: "Sample federal education institute",
    pathway: "vocational",
    status: "open",
    statusNote: "Applications shown open in prototype scenario.",
    jurisdictionCode: "BR",
    jurisdictionName: "Brazil",
    scopeLabel: "Regional campus admission",
    outcome: "Recognised technical qualification",
    applicationWindow: { opensOn: "2026-09-17", closesOn: "2026-10-20", officialTimeZone: "America/Sao_Paulo", cutoffLocalTime: null, precision: "date" },
    qualifications: "Secondary education (sample rule)",
    citizenshipRule: "No citizenship determination in sample evidence.",
    residenceRule: "No residence determination in sample evidence.",
    selectionStages: ["Entrance examination", "Document verification"],
    fee: "Fee waiver categories need verification",
    venues: [{ kind: "published", name: "Sample institute campus", city: "Recife", latitude: -8.0476, longitude: -34.877 }],
    sources: [sampleSource("br-technical-training-2026", "Sample federal education institute", "Portuguese", "HTML")],
    changes: [{ at: "2026-09-17", kind: "created", summary: "Illustrative technical intake added." }],
  }),
  cycle({
    id: "fr-health-admission-2026",
    title: "Health sciences programme admission",
    cycleLabel: "2027 entry",
    programme: "Health sciences admission",
    authority: "Sample public university",
    pathway: "admission",
    status: "extended",
    statusNote: "Illustrative deadline extension from 26 September to 5 October.",
    jurisdictionCode: "FR",
    jurisdictionName: "France",
    scopeLabel: "University admission",
    outcome: "Admission to health sciences programme",
    applicationWindow: { opensOn: "2026-09-01", closesOn: "2026-10-05", officialTimeZone: "Europe/Paris", cutoffLocalTime: null, precision: "date" },
    qualifications: "Secondary qualification equivalence (sample rule)",
    citizenshipRule: "International categories need verification.",
    residenceRule: "Residence rule needs verification.",
    selectionStages: ["Application review", "Academic selection"],
    fee: "Fee not verified",
    venues: [{ kind: "unknown", name: "Selection venue not published" }],
    sources: [sampleSource("fr-health-admission-2026", "Sample public university", "French", "PDF")],
    changes: [{ at: "2026-09-21", kind: "extended", summary: "Illustrative closing date moved from 26 September to 5 October." }],
  }),
  cycle({
    id: "fr-accountancy-license-2026",
    title: "Accountancy credential examination",
    cycleLabel: "2026 session",
    programme: "Accountancy credential",
    authority: "Sample professional authority",
    pathway: "licensing",
    status: "closed",
    statusNote: "Sample registration window ended 12 September.",
    jurisdictionCode: "FR",
    jurisdictionName: "France",
    scopeLabel: "National regulatory scope",
    outcome: "Professional accountancy credential eligibility",
    applicationWindow: { opensOn: "2026-07-20", closesOn: "2026-09-12", officialTimeZone: "Europe/Paris", cutoffLocalTime: null, precision: "date" },
    qualifications: "Approved academic credits (sample rule)",
    citizenshipRule: "No citizenship determination in sample evidence.",
    residenceRule: "No residence determination in sample evidence.",
    selectionStages: ["Document review", "Written examination"],
    fee: "Fee not verified",
    venues: [{ kind: "published", name: "Sample assessment centre", city: "Paris", latitude: 48.8566, longitude: 2.3522 }],
    sources: [sampleSource("fr-accountancy-license-2026", "Sample professional authority", "French", "scanned PDF")],
    changes: [{ at: "2026-07-20", kind: "created", summary: "Illustrative examination session added." }],
  }),
  cycle({
    id: "jp-municipal-recruitment-2026",
    title: "Municipal administration intake",
    cycleLabel: "2026 examination",
    programme: "Municipal recruitment",
    authority: "Sample municipal government",
    pathway: "recruitment",
    status: "stale",
    statusNote: "Sample source checks failed; prior revision retained.",
    jurisdictionCode: "JP",
    jurisdictionName: "Japan",
    scopeLabel: "Municipal hiring scope",
    outcome: "Municipal government appointment",
    applicationWindow: { opensOn: "2026-09-04", closesOn: "2026-09-28", officialTimeZone: "Asia/Tokyo", cutoffLocalTime: null, precision: "date" },
    qualifications: "Age and education rules need verification.",
    citizenshipRule: "Nationality rule needs verification.",
    residenceRule: "Municipal residence rule needs verification.",
    selectionStages: ["Written examination", "Interview"],
    fee: "Fee not verified",
    venues: [{ kind: "unknown", name: "Exam venue not published" }],
    sources: [sampleSource("jp-municipal-recruitment-2026", "Sample municipal government", "Japanese", "HTML", "2026-09-19T04:00:00Z")],
    changes: [{ at: "2026-09-22", kind: "source-failure", summary: "Illustrative source check failed; no closure inferred." }],
  }),
  cycle({
    id: "jp-skills-test-2026",
    title: "Industrial skills certification",
    cycleLabel: "Winter 2026",
    programme: "Industrial skills qualification",
    authority: "Sample public skills agency",
    pathway: "vocational",
    status: "uncertain",
    statusNote: "Sample translation leaves selection rules unresolved.",
    jurisdictionCode: "JP",
    jurisdictionName: "Japan",
    scopeLabel: "Prefectural qualification scope",
    outcome: "Recognised vocational skills certificate",
    applicationWindow: { opensOn: "2026-09-20", closesOn: null, officialTimeZone: "Asia/Tokyo", cutoffLocalTime: null, precision: "unknown" },
    qualifications: "Prior practice experience needs verification.",
    citizenshipRule: "No citizenship determination in sample evidence.",
    residenceRule: "Prefectural eligibility needs verification.",
    selectionStages: ["Document review", "Practical skills test"],
    fee: "Fee not verified",
    venues: [{ kind: "unknown", name: "Practical test venue not published" }],
    sources: [sampleSource("jp-skills-test-2026", "Sample public skills agency", "Japanese", "scanned PDF")],
    changes: [{ at: "2026-09-23", kind: "eligibility", summary: "Illustrative translation ambiguity sent to review." }],
  }),
  cycle({
    id: "jp-engineering-admission-2026",
    title: "Public engineering school admission",
    cycleLabel: "2027 entry",
    programme: "Engineering degree admission",
    authority: "Sample public university",
    pathway: "admission",
    status: "open",
    statusNote: "Applications shown open in prototype scenario.",
    jurisdictionCode: "JP",
    jurisdictionName: "Japan",
    scopeLabel: "University admission",
    outcome: "Admission to engineering degree programme",
    applicationWindow: { opensOn: "2026-09-15", closesOn: "2026-10-30", officialTimeZone: "Asia/Tokyo", cutoffLocalTime: null, precision: "date" },
    qualifications: "Upper secondary equivalence (sample rule)",
    citizenshipRule: "International category needs verification.",
    residenceRule: "No residence determination in sample evidence.",
    selectionStages: ["Document review", "Entrance examination"],
    fee: "Fee not verified",
    venues: [{ kind: "online", name: "Initial document screening online" }, { kind: "published", name: "Sample examination campus", city: "Tokyo", latitude: 35.6762, longitude: 139.6503 }],
    sources: [sampleSource("jp-engineering-admission-2026", "Sample public university", "Japanese", "HTML")],
    changes: [{ at: "2026-09-15", kind: "created", summary: "Illustrative admissions cycle added." }],
  }),
];

export const fixtureCoverage: CoverageRecord[] = [
  { jurisdictionCode: "IN", fixture: true, status: "no-verified-listings", researchedAuthorities: ["Sample national recruitment authority", "Sample state licensing board"], connectedSourceCount: 0, unresolvedGaps: ["Real source registry not connected"], lastSuccessfulFetchAt: null, lastValidatedAt: null },
  { jurisdictionCode: "US", fixture: true, status: "sources-checked-no-current", researchedAuthorities: ["Sample federal agency", "Sample public workforce office"], connectedSourceCount: 2, unresolvedGaps: ["Illustrative checked state only"], lastSuccessfulFetchAt: "2026-09-24T07:00:00Z", lastValidatedAt: "2026-09-24T07:20:00Z" },
  { jurisdictionCode: "GB", fixture: true, status: "verified-listings", researchedAuthorities: ["Sample central recruitment team", "Sample professional regulator"], connectedSourceCount: 2, unresolvedGaps: ["Regulator source failure in sample"], lastSuccessfulFetchAt: "2026-09-24T08:00:00Z", lastValidatedAt: "2026-09-24T08:10:00Z" },
  { jurisdictionCode: "BR", fixture: true, status: "no-verified-listings", researchedAuthorities: ["Sample state health secretariat", "Sample federal education institute"], connectedSourceCount: 0, unresolvedGaps: ["Portuguese document review pending in prototype"], lastSuccessfulFetchAt: null, lastValidatedAt: null },
  { jurisdictionCode: "FR", fixture: true, status: "sources-checked-no-current", researchedAuthorities: ["Sample public university", "Sample professional authority"], connectedSourceCount: 2, unresolvedGaps: ["Illustrative checked state only"], lastSuccessfulFetchAt: "2026-09-24T06:00:00Z", lastValidatedAt: "2026-09-24T06:15:00Z" },
  { jurisdictionCode: "JP", fixture: true, status: "no-verified-listings", researchedAuthorities: ["Sample municipal government", "Sample public skills agency"], connectedSourceCount: 0, unresolvedGaps: ["Translation and scanned document review pending in prototype"], lastSuccessfulFetchAt: null, lastValidatedAt: null },
];